quote = zoho.crm.getRecordById("Quotes",quoteId);
// info dealrecord;
dealId = quote.get('Deal_Name').get("id");
deals = zoho.crm.getRecordById("Deals",dealId);
dealrecord = zoho.crm.getRelatedRecords("Quotes","Deals",dealId);
// info deals;
deal_auto_number = deals.get("Deal_Number").toText();
deal_count = deal_auto_number.substring(15,-1);
// info deal_count;
deal_year = deal_auto_number.subString(3,14).toDate().getYear().toText();
// info deal_year;
quote_count = zoho.crm.getRelatedRecords("Quotes","Deals",dealId).size().toText();
quote_auto_number = "Q0-Q1-" + deal_year + "-" + deal_count + "-V" + quote_count;
// info quote_auto_number;
quoteMap = Map();
quoteMap.put("Quote_Auto_Number",quote_auto_number);
quote = zoho.crm.updateRecord("Quotes",quoteId,quoteMap);
info quote;
info quoteMap;